version: "3.7"

networks:
    laravel-app-network:

services:
    mysql:
        image: mariadb:10.4
        container_name: application_mysql
        restart: unless-stopped
        tty: true
        ports:
            -  "3307:3306"
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel-app-network
    php:
        build:
            args:
                user: taylor
                uid: 1000
            context: .
            dockerfile: ./php/Dockerfile
        container_name: ph
        ports:
            - "9000:9000"
        volumes:
            -   ../src:/var/www/html
        networks:
            - laravel-app-network
    nginx:
        image: nginx:1.17-alpine
        container_name: application_nginx
        ports:
            - "8088:80"
            - "443:443"
        volumes:
            - ../src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel-app-network
    mongo:
        image: mongo:latest
        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - ./database/mongodb/db:/data/db
            - ./database/mongodb/dev.archive:/Databases/dev.archive
            - ./database/mongodb/production:/Databases/production
        command: [ --auth ]
        networks:
            - laravel-app-network
    mongo-express:
        image: mongo-express
        container_name: mexpress
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_EXPRESS_USERNAME}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_EXPRESS_PASSWORD}
            - ME_CONFIG_MONGODB_URL=${MONGO_EXPRESS_URL}
            - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_BASICAUTH_USERNAME}
            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_BASICAUTH_PASSWORD}
        links:
            - mongo
        restart: unless-stopped
        ports:
            - "8081:8081"
        networks:
            - laravel-app-network
